### ISSUE TITLE
Rest api 질문드려도 될까요?

### ISSUE THREAD

**Issue by SangHakLee** [iamport/iamport-manual#1]
https://api.iamport.kr/ 에서 RestApi 예제
swagger 쓰신건가요?

**Comment by jangbora** [comment]
네 swagger2.0 스펙으로 json을 전달받고 있고, swagger-ui 로 화면구성을 하였습니다.

**Comment by SangHakLee** [comment]
apiDocs가 간결하고 문법이 쉬워서 사용하려다 기존에 있는 rest 문서에 샘플로 보내는 코드만 
넣고 싶은데 잘 안되서 iamport Rest 문서 생각나 찾아봤더니 제가 딱 원하는 UI입니다.

apiDocs만 봐서 swagger는 대충 개념만 아는데 혹시 하다 모르는게 있으면 여기에 질문을 드려도 될까요?

**Comment by jangbora** [comment]
안녕하세요. 본래의 이 github과는 거리가 있는 것 같아, jang@siot.do 로 직접 연락주시면 최대한 답변드릴 수 있도록 하겠습니다. 감사합니다.

**Comment by SangHakLee** [comment]
네 감사합니다.
최대한 찾아서 해보고 혹시 막히는 부분이 있으면
연락드리겠습니다.
