### ISSUE TITLE
핸드폰 번호 필드 문의?

### ISSUE THREAD

**Issue by xkguq007** [iamport/iamport-manual#10]
certifications/imp_uid 정보에도 없는거 같은데 어디서 핸드폰 실제 번호는 얻을 수 잇나요?
danal측으로 불려지는 dom값을 얻어온다던가, 이쪽 form에서 입력받은 핸드폰 번호를 넘겨준다던가
하는 방식은 없나요?

**Comment by jangbora** [comment]
휴대폰 본인인증 시작 전, 개인정보 수집동의를 받으시는 조건하에 통신사에서 해당 필드를 열어주게 됩니다. (phone, carrier필드가 추가됩니다)
다날 계약진행하실 때 혹은 후에 사업자등록번호 혹은 CPID를 알려주시면 고객센터에서 등록진행을 도와드립니다.

**Comment by xkguq007** [comment]
넵 알겠습니다. 이슈 닫겠습니다.
