### ISSUE TITLE
가상계좌 결제 관련 문의

### ISSUE THREAD

**Issue by dizy64** [iamport/iamport-manual#17]
메뉴얼에 보면 아래처럼 되어있는데요.

vbank_due | string | 가상계좌 입금기한 | undefined | (선택항목) YYYYMMDDhhmm 형식 | 1.0.0부터
-- | -- | -- | -- | -- | --

1. 실제로는 무조건 자정까지 계좌가 열려있는 것 같던데 어떤게 정확한건가요?
2. 그렇다면 밤 11시쯤 가상계좌를 신청하는 경우에는 1시간 미만 내에 입금이 가능한 형태가 되는건가요?
3. 1시간 이내에만 가상계좌를 열기 같은 옵션은 따로 둘 수 없는건가요?

**Comment by jangbora** [comment]
이용하시는 PG사에 따라 hhmm 부분을 무시하고 YYYYMMDD만 인정하는 곳이 있습니다. 
혹시 JTNet을 이용 중이신가요?

**Comment by dizy64** [comment]
@jangbora 앗, 빠른 답변 감사합니다. 저희는 현재 다날을 사용하고 있습니다.

**Comment by jangbora** [comment]
네, 다날도 hhmm을 무시하고 YYYYMMDD만 인정하는 PG사에 해당됩니다. 

시간 / 분단위까지 지정을 원하신다면 KG이니시시 / KCP / 나이스페이먼츠 를 통해 진행을 해주셔야할 것 같습니다.

**Comment by dizy64** [comment]
감사합니다.
