### ISSUE TITLE
콜백요청 문의입니다.

### ISSUE THREAD

**Issue by TigerWest** [iamport/iamport-manual#21]
도입하기전이고 반응형 웹으로 구현할생각인데 pc화면에서 m_redirect_url을 준다면 동작이 어떻게 되나요?
```
IMP.request_pay({
    m_redirect_url : 'https://www.yourdomain.com/payments/complete',
}, function(rsp) {

});
```
기대하는 동작은 m_redirect_url을 무시하고 결제화면 띄워진후에 성공하면 콜백실행하기를 원하는건데
만약 m_redirect_url을 pc화면에서준다면 예외없이 redirect_url로 이동하나요?

**Comment by jangbora** [comment]
PC페이지에서 결제가 진행되는 경우에는 m_redirect_url 파라메터가 선언돼있어도 무시하게 됩니다. 
단, 예외적으로 Paypal 의 경우에는 PC/모바일 모두 결제가 시작되면 곧바로 Paypal 도메인으로 리디렉션돼버리는 정책을 가지고 있어 콜백이 근본적으로 불가능하므로 PC에서도 m_redirect_url이 사용됩니다.
