### ISSUE TITLE
나이스페이먼츠 비인증결제 문의입니다.

### ISSUE THREAD

**Issue by Bang9** [iamport/iamport-manual#23]
![image](https://user-images.githubusercontent.com/26326015/74230493-d6ad1a80-4d07-11ea-8a0c-3314c190281c.png)

정상적인 카드번호인 XXXX-XXXX-XXXX-XXXX 뒷부분에 숫자를 더 붙여서 등록요청을 할 경우에
 ex) `XXXX-XXXX-XXXX-XXXX-1234-1234-1234-1234`

등록된 카드번호가 아래와 같이 반환됩니다.
`XXXX-XXXX-XXXX-XXXX-1234`

의도된 동작인지 아닌지 궁금합니다.

**Comment by jangbora** [comment]
16자리를 초과하는 카드번호는 세상에 존재하지 않기 때문에 (특수기호 제외)숫자 개수가 16개를 넘어가면 truncate 처리하고 PG사에 요청합니다.

**Comment by Bang9** [comment]
답변 감사합니다!
그럼 아임포트쪽에 20자리까지 카드 번호가 저장되는것은 별다른 이유 없이
그냥 저장가능한 maxLength 를 20자리 까지로 설정해놔서라고 생각하면 될까요?

**Comment by jangbora** [comment]
저희 API문서상 card_number 필드의 max length 가 20으로 선언되어있어서 문의주시는 걸까요?

**Comment by Bang9** [comment]
문서에 별다른 길이제한은 안보였던 것 같습니다. 당연히 16자리까지만 저장이 될거라 생각했는데
카드번호가 20자리까지 저장이 된 뒤에 반환이 되길래 의도된 동작인지, 버그인지 헷갈려 문의를 드렸습니다.
생각해보니 별다른 문제가 될 건 없을 것 같습니다! 감사합니다.
