### ISSUE TITLE
안녕하세요, 빌링결제 API 관련 문의입니다.

### ISSUE THREAD

**Issue by Bang9** [iamport/iamport-manual#24]
안녕하세요

결제 내역에서는 신용카드/체크카드 구분을 알 수 있던데
혹시 `GET /subscribe/customers/{customer_uid}` API 를 통해서 해당 정보를 얻거나
다른 방법으로 확인할 방법이 있을까요?
(체크카드일 경우 할부를 불가능하게 설정하는데 필요할 것 같아서 여쭤봅니다!)

좋은 서비스 만들어주셔서 감사합니다!

![image](https://user-images.githubusercontent.com/26326015/78970896-5a875580-7b45-11ea-8aca-f1332bb1fef0.png)

**Comment by jangbora** [comment]
안녕하세요, 관련해서 일부 PG사의 경우 데이터 수집이 제대로 안되고 있었네요. 보완하여 금주 중으로 패치하도록 하겠습니다. 죄송합니다!

**Comment by jangbora** [comment]
처리가 늦어져 죄송합니다! 내부 테스트까지 어느정도 마무리되었으니 내일 중에는 배포가 가능할 것 같습니다. 배포 후에 다시 안내드리겠습니다

**Comment by Bang9** [comment]
> 처리가 늦어져 죄송합니다! 내부 테스트까지 어느정도 마무리되었으니 내일 중에는 배포가 가능할 것 같습니다. 배포 후에 다시 안내드리겠습니다

감사합니다!

**Comment by jangbora** [comment]
@Bang9 나이스페이먼츠 빌링등록정보에 대해서 card_type 을 수집하고, 조회 등 응답시에도 제공하도록 패치 완료되었습니다. 안타깝습니다만, 기존에 지나간 (이미 등록된 customer_uid)에 대해서는 정보가 없어 null 로 내려가게 됩니다. 양해부탁드립니다.

**Comment by Bang9** [comment]
> @Bang9 나이스페이먼츠 빌링등록정보에 대해서 card_type 을 수집하고, 조회 등 응답시에도 제공하도록 패치 완료되었습니다. 안타깝습니다만, 기존에 지나간 (이미 등록된 customer_uid)에 대해서는 정보가 없어 null 로 내려가게 됩니다. 양해부탁드립니다.

@jangbora 아직 개발중이어서 문제 될 사항은 없을 것 같습니다. ㅎㅎ 빠른 대응 감사합니다!
