### ISSUE TITLE
결제API 호출시 쿠키관련 이슈 sameSite

### ISSUE THREAD

**Issue by hyu-dev** [iamport/iamport-manual#29]
테스트 중에 쿠키관련 이슈가 발생하여 문의드립니다.
현재 저희 웹페이지에 조회수 계산을 위한 HTTPServlet Cookie를 사용하고 있습니다.
해당 클래스때문인지 api호출이 계속 실패하는 오류가 발생하는데요..
어떻게 해결이 가능할지 문의드립니다.
관련 이미지 첨부드립니다.
![image](https://user-images.githubusercontent.com/70465838/114143206-d1208400-994e-11eb-8911-1aeb34328b29.png)

**Comment by minseolee** [comment]
안녕하세요. 혹시 해결 하셨을까요 ?

**Comment by hyu-dev** [comment]
아 네넵 보니까 모든쿠키허용하고 그 서비스내에서 사용하기 위해 등록해야하는 기능들 다시 등록하니까 그다음부터 잘 되더라구요

2021년 8월 4일 (수) 14:24, Minseo Lee ***@***.***>님이 작성:
