### ISSUE TITLE
m_redirect_url이 존재하나 이미 결제된 건의 재요청시 해당 에러 메시지 확인 방법

### ISSUE THREAD

**Issue by yomybaby** [iamport/iamport-manual#6]
@jangbora 님과 메일로 주고 받은 내용이나 진행상황 확인 및 다른 개발자분들과 의견 교류 목적으로 이슈를 발급합니다.

## 원래 질문
모바일에서 m_redirect_url이 호출되지 않는 경우가 있습니다.
해당 경우는 이미 결제가 된 사항을 다시 요청했을 때 입니다.

이런 경우 m_redirect_url 리다이렉트 되면서 결과가 전달되는 것이 아니라 callback으로만 전달 됩니다.

```
{"{\"success\":false,\"request_id\":\"req_xxxxxxxx\",\"error_code\":\"F1002\",\"error_msg\":\"이미 결제가 이루어진 거래건입니다.\"}":""}
```

## @jangbora 님 답변
> 모바일 결제(PC결제 제외)에서 IMP.request_pay(param, callback) 시 callback이 선언되어있지 않다면 강제로 m_redirect_url로 동일하게 받으실 수 있도록 인터페이스를 변경하면 어떨까요?

## 추가적인 제 의견
이에 동의 합니다.
- 우선적으로 동일한 인터페이스라는 점과
- 앱의 webview내부에서 앱(네이티브)로 데이터를 보낼 때 url을 이용하는 방법이 널리쓰이고 있으니
“m_redirect_url”로 통일하는데 찬성합니다.

**Comment by jangbora** [comment]
관련해서 정리된 스펙을 업데이트하였습니다. 논의된대로,

1. 모바일 결제시
2. IMP.request_pay(param) 과 같이 callback이 누락되었고
3. 결제프로세스 시작 사전단계에서 실패사유가 발생하는 경우(이미 결제된 merchant_uid사용, 결제요청 파라메터 오류 등)

m_redirect_url 로 redirect되도록 수정하였습니다. 
해당 기능은 iamport.payment-1.1.5.js부터 적용됩니다. 

bec355c960dfcdf4a99db97f2d4a5d32653701a9
