### ISSUE TITLE
CI, DI값 제공여부 문의

### ISSUE THREAD

**Issue by why2pac** [iamport/iamport-manual#9]
SMS본인인증에서 CI, DI값이 응답 json에 포함되어 있지 않는 것으로 확인됩니다.

CI, DI값을 별도로 제공하지 않는것인가요?

**Comment by jangbora** [comment]
내부적으로는 CI, DI를 보관하고 있습니다만, 가맹점에서 요구하시는 경우가 없어 불필요한 정보로 판단해 응답 json스펙에 포함하지는 않았습니다. 혹시 해당 필드를 어떠한 용도로 사용하시려는지요?

**Comment by why2pac** [comment]
일반적으로 SMS본인인증 후 중복가입 여부를 확인하기 위해서 CI, DI값을 이용하도록 되어있어서 문의드렸습니다.

**Comment by jangbora** [comment]
그런 용도로 활용하실 수 있으실 것 같네요. 관련해서 스펙 추가할 수 있도록 하겠습니다.

**Comment by why2pac** [comment]
@jangbora 감사합니다.

**Comment by jangbora** [comment]
스펙 추가되었습니다. CI는 unique_key라는 key값으로, DI 는 unique_in_site라는 key값으로 제공되고 있습니다.

**Comment by kimja7045** [comment]
unique_key값을 주민등록번호 숫자로 변환가능한가요? 그렇다면 어떻게 변환할 수 있을까요?
